name: Kripto Gunluk Rapor

on:
  schedule:
    # UTC saatiyle 06:00 (Türkiye saatiyle 09:00)
    - cron: '58 23 * * *'
  
  # Manuel tetikleme
  workflow_dispatch:

jobs:
  run-crypto-bot:
    runs-on: self-hosted
    
    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      # HATA ÇIKARAN "setup-python" ADIMINI SİLDİM.
      # Kendi bilgisayarındaki Python'u kullanacağız.

      - name: Kütüphaneleri Yükle
        # Mac'te genellikle 'pip' yerine 'pip3' kullanılır, garanti olsun diye python3 modülü olarak çağırıyoruz.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests pybit pandas

      - name: Botu Çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # Mac'te 'python' komutu bazen Python 2'yi işaret edebilir, 'python3' kullanıyoruz.
        run: python3 main.py
